#Requires -Version 5.1
<#
.SYNOPSIS
    Alife Build Script - Build or Publish all projects
.DESCRIPTION
    Builds or publishes Client, DeskPet, and all Function plugins.
    Copies plugin files and syncs shared NuGet dependencies.
.PARAMETER Mode
    "build" (default) or "publish".
.PARAMETER OutputDir
    Output directory. Defaults to "Outputs" for build mode.
.EXAMPLE
    .\Build.ps1
    .\Build.ps1 -Mode publish -OutputDir "C:\path\to\dist\Outputs"
#>

param(
    [string]$Mode = "build",
    [string]$OutputDir = ""
)

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot
$Src = Join-Path $Root "Sources"

if (-not $OutputDir) {
    $OutputDir = Join-Path $Root "Outputs"
}

# Resolve to absolute path before any operations
$OutputDir = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutputDir)
$PluginTarget = Join-Path (Split-Path $OutputDir -Parent) "Storage\Plugins"

Write-Host "===================================================" -ForegroundColor Cyan
Write-Host "[Alife] $Mode Mode"                                    -ForegroundColor Cyan
Write-Host "===================================================" -ForegroundColor Cyan
Write-Host "[Alife] Output:      $OutputDir"                       -ForegroundColor Cyan
Write-Host "[Alife] PluginTarget: $PluginTarget"                    -ForegroundColor Cyan
Write-Host ""

# ============================================================
# Step 0: Clean output directory
# ============================================================
Write-Host "[0/3] Cleaning output directory..." -ForegroundColor Yellow

if (Test-Path $OutputDir) { Remove-Item $OutputDir -Recurse -Force }
New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
Write-Host "  Cleaned: $OutputDir" -ForegroundColor Green
Write-Host ""

# ============================================================
# Step 1: Build or Publish
# ============================================================
Write-Host "[1/3] $Mode applications..." -ForegroundColor Yellow

$buildCmd = if ($Mode -eq "publish") { "publish" } else { "build" }
$ridArg = if ($Mode -eq "publish") { @("-r", "win-x64") } else { @() }

Write-Host "  $Mode Alife.Client..."
dotnet $buildCmd (Join-Path $Src "Alife\Alife.Client\Alife.Client.csproj") `
    -c Release -o (Join-Path $OutputDir "Alife.Client") --self-contained false @ridArg -nologo --verbosity quiet

Write-Host "  $Mode Alife.DeskPet.Client..."
dotnet $buildCmd (Join-Path $Src "Alife.DeskPet\Alife.DeskPet.Client\Alife.DeskPet.Client.csproj") `
    -c Release -o (Join-Path $OutputDir "Alife.DeskPet.Client") --self-contained false @ridArg -nologo --verbosity quiet

$functionDirs = Get-ChildItem (Join-Path $Src "Alife.Function") -Directory | Where-Object { $_.Name -match '^Alife\.Function\.' }
foreach ($dir in $functionDirs) {
    $csproj = Join-Path $dir.FullName "$($dir.Name).csproj"
    $funcOut = Join-Path $OutputDir $dir.Name
    Write-Host "  $Mode $($dir.Name)..."
    dotnet $buildCmd $csproj -c Release -o $funcOut @ridArg -nologo --verbosity quiet
}

Write-Host ""

# ============================================================
# Step 2: Copy plugins
# ============================================================
Write-Host "[2/3] Copying plugins..." -ForegroundColor Yellow

if (Test-Path $PluginTarget) {
    Remove-Item $PluginTarget -Recurse -Force
}
New-Item -ItemType Directory -Path $PluginTarget -Force | Out-Null

$runtimeGlobalUsings = @'
// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Text;
global using global::System.Text.RegularExpressions;
global using global::System.Threading;
global using global::System.Threading.Tasks;
'@
Set-Content -LiteralPath (Join-Path $PluginTarget "RuntimeGlobalUsings.g.cs") -Value $runtimeGlobalUsings -Encoding UTF8

foreach ($dir in $functionDirs) {
    $target = Join-Path $PluginTarget $dir.Name
    New-Item -ItemType Directory -Path $target -Force | Out-Null

    # Copy .cs files from source directory
    Get-ChildItem $dir.FullName -Filter "*.cs" -File | ForEach-Object {
        Copy-Item $_.FullName $target -Force
    }

    # Copy generated Razor .g.cs files (only if corresponding .razor exists)
    $generatedDir = Join-Path $dir.FullName "obj\Release\generated\Microsoft.CodeAnalysis.Razor.Compiler"
    if (Test-Path $generatedDir) {
        Get-ChildItem $generatedDir -Filter "*_razor.g.cs" -Recurse -File | ForEach-Object {
            $razorName = $_.Name -replace '_razor\.g\.cs$', ''
            $razorFile = Join-Path $dir.FullName "$razorName.razor"
            if (Test-Path $razorFile) {
                Copy-Item $_.FullName $target -Force
            } else {
                Write-Host "  [skip] $($_.Name)"
            }
        }
    }

    # Copy non-Razor source-generator outputs such as GeneratedRegex implementations.
    $generatedRoot = Join-Path $dir.FullName "obj\Release\generated"
    if (Test-Path $generatedRoot) {
        Get-ChildItem $generatedRoot -Filter "*.g.cs" -Recurse -File |
            Where-Object { $_.FullName -notlike "*Microsoft.CodeAnalysis.Razor.Compiler*" } |
            ForEach-Object {
                $relativePath = $_.FullName.Substring($generatedRoot.Length + 1)
                $destPath = Join-Path $target (Join-Path "Generated" $relativePath)
                $destDir = Split-Path $destPath -Parent

                if (-not (Test-Path $destDir)) {
                    New-Item $destDir -ItemType Directory -Force | Out-Null
                }

                Copy-Item $_.FullName $destPath -Force
            }
    }

    Write-Host "  [done] $($dir.Name)" -ForegroundColor Green
}
Write-Host ""

# ============================================================
# Step 3: Sync NuGet dependencies
# ============================================================
Write-Host "[3/3] Syncing NuGet deps..." -ForegroundColor Yellow

$nuGetDir = Join-Path $PluginTarget "BaseDirectory"
New-Item -ItemType Directory -Path $nuGetDir -Force | Out-Null

$clientDir = Join-Path $OutputDir "Alife.Client"
$functionOutputDirs = Get-ChildItem $OutputDir -Directory | Where-Object { $_.Name -match '^Alife\.Function\.' }

foreach ($funcDir in $functionOutputDirs) {
    $files = Get-ChildItem $funcDir.FullName -Recurse -File
    foreach ($file in $files) {
        # Skip Alife.Function.* assemblies (already in plugin dir)
        if ($file.Name -match '^Alife\.Function\.') { continue }
        # Skip files that already exist in Client output
        if (Test-Path (Join-Path $clientDir $file.Name)) { continue }

        $relativePath = $file.FullName.Substring($funcDir.FullName.Length + 1)
        $destPath = Join-Path $nuGetDir $relativePath
        $destDir = Split-Path $destPath -Parent

        if (-not (Test-Path $destDir)) {
            New-Item $destDir -ItemType Directory -Force | Out-Null
        }

        Copy-Item $file.FullName $destPath -Force
        Write-Host "  [sync] $relativePath"
    }
}

# Clean non-Client output directories (publish mode only)
if ($Mode -eq "publish") {
    Write-Host ""
    Write-Host "  Cleaning non-Client outputs..."
    Get-ChildItem $OutputDir -Directory | Where-Object { $_.Name -notin @("Alife.Client", "Alife.DeskPet.Client") } | ForEach-Object {
        Remove-Item $_.FullName -Recurse -Force
    }
}

Write-Host ""
Write-Host "===================================================" -ForegroundColor Green
Write-Host "[Success] $Mode complete!"                              -ForegroundColor Green
Write-Host "  Plugins: $PluginTarget"                               -ForegroundColor Green
Write-Host "  NuGet:   $nuGetDir"                                   -ForegroundColor Green
Write-Host "===================================================" -ForegroundColor Green
