using Npgsql;

namespace Alife.Function.DataAgent;

public sealed class PostgresDataAgentStore : IDataAgentStore
{
    readonly string connectionString;

    public PostgresDataAgentStore(string connectionString)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(connectionString);

        this.connectionString = connectionString;
    }

    public string ProviderName => "postgres";

    public void Initialize()
    {
        using NpgsqlConnection connection = Open();
        using NpgsqlCommand command = connection.CreateCommand();
        command.CommandText = """
            CREATE TABLE IF NOT EXISTS engineering_gate (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                category TEXT NOT NULL,
                required BOOLEAN NOT NULL,
                status TEXT NOT NULL,
                evidence_path TEXT NOT NULL,
                last_checked_at TEXT NOT NULL,
                source TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS runtime_readiness_check (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                capability TEXT NOT NULL,
                account TEXT NOT NULL,
                endpoint TEXT NOT NULL,
                status TEXT NOT NULL,
                required BOOLEAN NOT NULL,
                failure_reason TEXT NOT NULL,
                last_checked_at TEXT NOT NULL,
                evidence_path TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS module_capability (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                module_name TEXT NOT NULL,
                capability_name TEXT NOT NULL,
                required BOOLEAN NOT NULL,
                status TEXT NOT NULL,
                test_project TEXT NOT NULL,
                evidence_path TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS test_run (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                suite_name TEXT NOT NULL,
                passed INTEGER NOT NULL,
                failed INTEGER NOT NULL,
                skipped INTEGER NOT NULL,
                total INTEGER NOT NULL,
                ran_at TEXT NOT NULL,
                command TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS document_index (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                path TEXT NOT NULL,
                doc_type TEXT NOT NULL,
                title TEXT NOT NULL,
                summary TEXT NOT NULL,
                tags TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS query_audit (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                question TEXT NOT NULL,
                dataset TEXT NOT NULL,
                query_plan_json TEXT NOT NULL,
                generated_sql TEXT NOT NULL,
                validated BOOLEAN NOT NULL,
                rejected_reason TEXT NOT NULL,
                row_count INTEGER NOT NULL,
                elapsed_ms BIGINT NOT NULL,
                created_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS tool_broker_audit (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                session_id TEXT NOT NULL,
                tool_name TEXT NOT NULL,
                allowed BOOLEAN NOT NULL,
                reason_code TEXT NOT NULL,
                reason TEXT NOT NULL,
                created_at TEXT NOT NULL
            );
            """;
        command.ExecuteNonQuery();
    }

    public void ImportFixtures()
    {
        string timestamp = new DateTimeOffset(2026, 6, 27, 0, 0, 0, TimeSpan.Zero).ToString("O");
        string readinessEvidencePath = "tools/check-qchat-runtime-readiness.ps1";
        string testRunCommand = "dotnet test Alife.slnx --no-restore --no-build -v:minimal";
        string documentPath = "docs/superpowers/specs/2026-06-27-dataagent-nl2sql-design.md";

        using NpgsqlConnection connection = Open();
        Execute(
            connection,
            "DELETE FROM engineering_gate WHERE source = @source",
            new NpgsqlParameter("source", "fixture"));
        Execute(
            connection,
            "DELETE FROM runtime_readiness_check WHERE capability = @capability AND evidence_path = @evidence_path",
            new NpgsqlParameter("capability", "MixuTts9881Reachable"),
            new NpgsqlParameter("evidence_path", readinessEvidencePath));
        Execute(
            connection,
            "DELETE FROM test_run WHERE suite_name = @suite_name AND command = @command",
            new NpgsqlParameter("suite_name", "Alife.Test.QChat"),
            new NpgsqlParameter("command", testRunCommand));
        Execute(
            connection,
            "DELETE FROM document_index WHERE path = @path",
            new NpgsqlParameter("path", documentPath));

        Execute(
            connection,
            """
            INSERT INTO engineering_gate (name, category, required, status, evidence_path, last_checked_at, source)
            VALUES (@name, @category, @required, @status, @evidence_path, @last_checked_at, @source)
            """,
            new NpgsqlParameter("name", "Runtime readiness script"),
            new NpgsqlParameter("category", "Harness"),
            new NpgsqlParameter("required", true),
            new NpgsqlParameter("status", "passed"),
            new NpgsqlParameter("evidence_path", readinessEvidencePath),
            new NpgsqlParameter("last_checked_at", timestamp),
            new NpgsqlParameter("source", "fixture"));

        Execute(
            connection,
            """
            INSERT INTO engineering_gate (name, category, required, status, evidence_path, last_checked_at, source)
            VALUES (@name, @category, @required, @status, @evidence_path, @last_checked_at, @source)
            """,
            new NpgsqlParameter("name", "DataAgent readiness script"),
            new NpgsqlParameter("category", "Harness"),
            new NpgsqlParameter("required", false),
            new NpgsqlParameter("status", "missing"),
            new NpgsqlParameter("evidence_path", "tools/check-dataagent-readiness.ps1"),
            new NpgsqlParameter("last_checked_at", timestamp),
            new NpgsqlParameter("source", "fixture"));

        Execute(
            connection,
            """
            INSERT INTO runtime_readiness_check (capability, account, endpoint, status, required, failure_reason, last_checked_at, evidence_path)
            VALUES (@capability, @account, @endpoint, @status, @required, @failure_reason, @last_checked_at, @evidence_path)
            """,
            new NpgsqlParameter("capability", "MixuTts9881Reachable"),
            new NpgsqlParameter("account", "mixu"),
            new NpgsqlParameter("endpoint", "127.0.0.1:9881"),
            new NpgsqlParameter("status", "missing"),
            new NpgsqlParameter("required", true),
            new NpgsqlParameter("failure_reason", "mixu_tts_endpoint_unreachable"),
            new NpgsqlParameter("last_checked_at", timestamp),
            new NpgsqlParameter("evidence_path", readinessEvidencePath));

        Execute(
            connection,
            """
            INSERT INTO test_run (suite_name, passed, failed, skipped, total, ran_at, command)
            VALUES (@suite_name, @passed, @failed, @skipped, @total, @ran_at, @command)
            """,
            new NpgsqlParameter("suite_name", "Alife.Test.QChat"),
            new NpgsqlParameter("passed", (object)1168),
            new NpgsqlParameter("failed", (object)0),
            new NpgsqlParameter("skipped", (object)10),
            new NpgsqlParameter("total", (object)1178),
            new NpgsqlParameter("ran_at", timestamp),
            new NpgsqlParameter("command", testRunCommand));

        Execute(
            connection,
            """
            INSERT INTO document_index (path, doc_type, title, summary, tags, updated_at)
            VALUES (@path, @doc_type, @title, @summary, @tags, @updated_at)
            """,
            new NpgsqlParameter("path", documentPath),
            new NpgsqlParameter("doc_type", "spec"),
            new NpgsqlParameter("title", "DataAgent NL2SQL Design"),
            new NpgsqlParameter("summary", "DataAgent QueryPlan-first NL2SQL design."),
            new NpgsqlParameter("tags", "dataagent,nl2sql,chatbi"),
            new NpgsqlParameter("updated_at", timestamp));
    }

    public DataAgentQueryResult Query(DataAgentCompiledSql compiledSql)
    {
        ArgumentNullException.ThrowIfNull(compiledSql);

        using NpgsqlConnection connection = Open();
        using NpgsqlCommand command = connection.CreateCommand();
        command.CommandText = compiledSql.Sql;
        command.CommandTimeout = 5;

        foreach (DataAgentSqlParameter parameter in compiledSql.Parameters)
        {
            string parameterName = parameter.Name.StartsWith("@", StringComparison.Ordinal)
                ? parameter.Name[1..]
                : parameter.Name;
            command.Parameters.AddWithValue(parameterName, parameter.Value ?? DBNull.Value);
        }

        using NpgsqlDataReader reader = command.ExecuteReader();
        List<IReadOnlyDictionary<string, object?>> rows = [];

        while (reader.Read())
        {
            Dictionary<string, object?> row = new(StringComparer.OrdinalIgnoreCase);
            for (int i = 0; i < reader.FieldCount; i++)
                row[reader.GetName(i)] = reader.IsDBNull(i) ? null : reader.GetValue(i);

            rows.Add(row);
        }

        return new DataAgentQueryResult(rows);
    }

    public void RecordAccepted(DataAgentAcceptedAuditInput input)
    {
        ArgumentNullException.ThrowIfNull(input);

        InsertAudit(
            input.Question,
            input.Dataset,
            input.QueryPlanJson,
            input.GeneratedSql,
            true,
            string.Empty,
            input.RowCount,
            input.Elapsed);
    }

    public void RecordRejected(DataAgentRejectedAuditInput input)
    {
        ArgumentNullException.ThrowIfNull(input);

        InsertAudit(
            input.Question,
            input.Dataset,
            input.QueryPlanJson,
            input.GeneratedSql,
            false,
            input.RejectedReason,
            0,
            input.Elapsed);
    }

    public IReadOnlyList<DataAgentAuditRecord> ReadQueryAudit()
    {
        using NpgsqlConnection connection = Open();
        using NpgsqlCommand command = connection.CreateCommand();
        command.CommandText = """
            SELECT question, dataset, query_plan_json, generated_sql, validated, rejected_reason, row_count, elapsed_ms, created_at
            FROM query_audit
            ORDER BY id ASC
            """;

        using NpgsqlDataReader reader = command.ExecuteReader();
        List<DataAgentAuditRecord> records = [];

        while (reader.Read())
        {
            records.Add(new DataAgentAuditRecord(
                reader.GetString(0),
                reader.GetString(1),
                reader.GetString(2),
                reader.GetString(3),
                reader.GetBoolean(4),
                reader.GetString(5),
                reader.GetInt32(6),
                TimeSpan.FromMilliseconds(reader.GetInt64(7)),
                DateTimeOffset.Parse(reader.GetString(8))));
        }

        return records;
    }

    public void RecordToolBrokerAudit(DataAgentToolBrokerAuditRecord record)
    {
        ArgumentNullException.ThrowIfNull(record);

        using NpgsqlConnection connection = Open();
        Execute(
            connection,
            """
            INSERT INTO tool_broker_audit (session_id, tool_name, allowed, reason_code, reason, created_at)
            VALUES (@session_id, @tool_name, @allowed, @reason_code, @reason, @created_at)
            """,
            new NpgsqlParameter("session_id", record.SessionId),
            new NpgsqlParameter("tool_name", record.ToolName),
            new NpgsqlParameter("allowed", record.Allowed),
            new NpgsqlParameter("reason_code", record.ReasonCode),
            new NpgsqlParameter("reason", record.Reason),
            new NpgsqlParameter("created_at", record.CreatedAt.ToUniversalTime().ToString("O")));
    }

    public IReadOnlyList<DataAgentToolBrokerAuditRecord> ReadToolBrokerAudit()
    {
        using NpgsqlConnection connection = Open();
        using NpgsqlCommand command = connection.CreateCommand();
        command.CommandText = """
            SELECT session_id, tool_name, allowed, reason_code, reason, created_at
            FROM tool_broker_audit
            ORDER BY id ASC
            """;

        using NpgsqlDataReader reader = command.ExecuteReader();
        List<DataAgentToolBrokerAuditRecord> records = [];

        while (reader.Read())
        {
            records.Add(new DataAgentToolBrokerAuditRecord(
                reader.GetString(0),
                reader.GetString(1),
                reader.GetBoolean(2),
                reader.GetString(3),
                reader.GetString(4),
                DateTimeOffset.Parse(reader.GetString(5))));
        }

        return records;
    }

    NpgsqlConnection Open()
    {
        NpgsqlConnection connection = new(connectionString);
        connection.Open();
        return connection;
    }

    void InsertAudit(
        string question,
        string dataset,
        string queryPlanJson,
        string generatedSql,
        bool validated,
        string rejectedReason,
        int rowCount,
        TimeSpan elapsed)
    {
        using NpgsqlConnection connection = Open();
        Execute(
            connection,
            """
            INSERT INTO query_audit (question, dataset, query_plan_json, generated_sql, validated, rejected_reason, row_count, elapsed_ms, created_at)
            VALUES (@question, @dataset, @query_plan_json, @generated_sql, @validated, @rejected_reason, @row_count, @elapsed_ms, @created_at)
            """,
            new NpgsqlParameter("question", question),
            new NpgsqlParameter("dataset", dataset),
            new NpgsqlParameter("query_plan_json", queryPlanJson),
            new NpgsqlParameter("generated_sql", generatedSql),
            new NpgsqlParameter("validated", validated),
            new NpgsqlParameter("rejected_reason", rejectedReason),
            new NpgsqlParameter("row_count", rowCount),
            new NpgsqlParameter("elapsed_ms", checked((long)elapsed.TotalMilliseconds)),
            new NpgsqlParameter("created_at", DateTimeOffset.UtcNow.ToString("O")));
    }

    static void Execute(NpgsqlConnection connection, string commandText, params NpgsqlParameter[] parameters)
    {
        using NpgsqlCommand command = connection.CreateCommand();
        command.CommandText = commandText;

        foreach (NpgsqlParameter parameter in parameters)
            command.Parameters.Add(parameter);

        command.ExecuteNonQuery();
    }
}
