using Alife.Framework;
using Microsoft.Extensions.Logging.Abstractions;
using System.Runtime.Loader;

namespace Alife.Test.Framework;

public class ModuleSystemRuntimeCompilationTests
{
    [Test]
    public void CompileModuleFailureIncludesSourcePathAndFileCounts()
    {
        string sourceRoot = Path.Combine(Path.GetTempPath(), $"alife-module-broken-{Guid.NewGuid():N}");
        Directory.CreateDirectory(sourceRoot);
        try
        {
            File.WriteAllText(Path.Combine(sourceRoot, "BrokenModule.cs"), """
                using Alife.Framework;

                namespace DynamicPluginFixture;

                [Module("Broken runtime compile fixture", "Covers diagnostic details.")]
                public sealed class BrokenRuntimeCompileFixtureModule : ISystemEvent
                {
                    public string Broken => ;
                }
                """);

            ModuleSystem moduleSystem = new(new StorageSystem(), new NullLogger<ModuleSystem>());

            Exception ex = Assert.Throws<Exception>(() => moduleSystem.CompileModule(sourceRoot))!;

            Assert.That(ex.Message, Does.Contain(sourceRoot));
            Assert.That(ex.Message, Does.Contain("sourceFiles=1"));
            Assert.That(ex.Message, Does.Contain("dllFiles=0"));
            Assert.That(ex.Message, Does.Contain("BrokenModule.cs"));
        }
        finally
        {
            Directory.Delete(sourceRoot, recursive: true);
        }
    }

    [Test]
    public void CompileModuleSupportsRuntimeGlobalUsingsAndGeneratedFileLocalTypes()
    {
        string sourceRoot = Path.Combine(Path.GetTempPath(), $"alife-module-runtime-{Guid.NewGuid():N}");
        Directory.CreateDirectory(sourceRoot);
        try
        {
            File.WriteAllText(Path.Combine(sourceRoot, "RuntimeGlobalUsings.g.cs"), """
                // <auto-generated/>
                global using global::System.Collections.Generic;
                global using global::System.Threading.Tasks;
                """);

            File.WriteAllText(Path.Combine(sourceRoot, "GeneratedA.g.cs"), """
                namespace RuntimeGenerated;

                file sealed class SharedFileLocalName
                {
                    public static string Value => "a";
                }

                public static partial class GeneratedAccess
                {
                    public static string A() => SharedFileLocalName.Value;
                }
                """);

            File.WriteAllText(Path.Combine(sourceRoot, "GeneratedB.g.cs"), """
                namespace RuntimeGenerated;

                file sealed class SharedFileLocalName
                {
                    public static string Value => "b";
                }

                public static partial class GeneratedAccess
                {
                    public static string B() => SharedFileLocalName.Value;
                }
                """);

            File.WriteAllText(Path.Combine(sourceRoot, "RuntimeCompileFixtureModule.cs"), """
                using Alife.Framework;
                using RuntimeGenerated;

                namespace DynamicPluginFixture;

                [Module("Runtime compile fixture", "Covers runtime generated source compilation.")]
                public sealed class RuntimeCompileFixtureModule : ISystemEvent
                {
                    public IReadOnlyList<string> Values { get; } =
                        new List<string> { GeneratedAccess.A(), GeneratedAccess.B() };

                    public Task<string> SummarizeAsync() =>
                        Task.FromResult(string.Join(",", Values));
                }
                """);

            ModuleSystem moduleSystem = new(new StorageSystem(), new NullLogger<ModuleSystem>());
            AssemblyLoadContext context = moduleSystem.CompileModule(sourceRoot);
            try
            {
                Type? moduleType = context.Assemblies
                    .SelectMany(assembly => assembly.GetTypes())
                    .SingleOrDefault(type => type.FullName == "DynamicPluginFixture.RuntimeCompileFixtureModule");

                Assert.That(moduleType, Is.Not.Null);
                object instance = Activator.CreateInstance(moduleType!)!;
                object? result = moduleType!.GetMethod("SummarizeAsync")!.Invoke(instance, null);
                Assert.That(((Task<string>)result!).Result, Is.EqualTo("a,b"));
            }
            finally
            {
                context.Unload();
            }
        }
        finally
        {
            Directory.Delete(sourceRoot, recursive: true);
        }
    }
}
